endpoints/bahmni/input-mapping.json, package-lock.json, package.json
Forked original object mapper module to cater for our case.
We can't let users add their own transformation functions with risking
app security. Therefore to still allow transformations we have forker
the object mapper module and implemented a set of pre-existing functions
which can be called by providing a key which will fetch that function at
run time and use it to transform the users data.
This prevents malicious users executing code directly in the app
OHM-870# If applied, this commit will:
=> Use new object mapper module

endpoints/bahmni/meta.json, endpoints/openIMIS/meta.json
As this will not currently be used. We will only be accepting POST requests which contain the body payload to map data from.
In future additions we might be adding support for more methods and to forward the request onto a destination which would require additional methods.
OHM-875
=> OHM-875: Remove the methods from meta.json config

src/middleware/mapper.js, src/middleware/validator.js
Prior to this change, validator was returning an empty body when
validation processing failed
Assigning the error object that the exception handler catches
results in an empty response body.
This change adds the error message to the response body when a
validation exception causes a 4xx response to be returned
OHM-885
=> OHM-885 Fix to return response body when exception is thrown

endpoints/bahmni/input-validation.json
In the mapping rules, references to specific elements in the links arrays are made (identifiers[].links[0].uri: identifier[].system). A mapping failure occurs if the array is undefined. With other types, the mapping does not fail when a field is undefined. This is an issue with object-mapper.
OHM-842
=> make the links arrays required

src/config.js, src/index.js, src/openhim.js
Prior to this change, registration of the mediator with OpenHIM was
automatic, at mediator startup
This change introduces a configuration flag to indicate whether
to register this mediator with a running OpenHIM instance (true)
or not (false). The default value for the flag is true.
OHM-877
=> OHM-877 Split out mediator registration and make it optional

src/middleware/parser.js
The expected incoming body type was being set to the value of the incoming content type. This was resulting in routes accepting all content types, as the comparizon between the expected input type and the content type was yielding true all the times. The expected incoming type should be set to the transformation input value from the metadata.
OHM-894
=> correctly set the expected incoming body type

src/middleware/externalRequests.js, tests/unit/externalRequestsTest.js
Users can now define what statuses are valid responses from downstream
services.
Wildcards can be used to declare valid ranges
OHIE-298
=> OHIE-298 failure rules

docs/docs/setup.md
The TRUST_SELF_SIGNED env var defaults to true in the code but the docs
were the ooposite.
The VALIDATION_ACCEPT_NULL_VALUES is also vice versa
It's confusing!!!!
TRACE-113
=> TRACE-113 Fix docs to match the code

src/middleware/initiate.js
It was thrown an error not being able to access a property of undefined
=> Fixed bug with updating the endpoint state if no extract is supplied

tests/integration/mapper.js, tests/unit/parser.js
The message returned when there is a mapping error was made more verbose and this requires the tests to be modified
OHM-998
=> fix broken test

tests/integration/parser.js
The endpoints for creating and updating an endpoint were hanging when a request body was not supplied. Logic to fix the hanging has been added in this commit
OHM-1013
=> fix the hanging on create and update endpoints

src/db/models/endpoints.js
This is so we have exact matching in the regex that checks the uniqueness of a pattern before endpoint creation
=> add closing and opening tags for regex

src/middleware/externalRequests.js, tests/unit/externalRequests.js
Building query parameters requires access to all available variables.
Previously data within these objects would have been unavailable
TRACE-156
=> TRACE-156 Make constants and timestamps available to extractparamValue function

src/db/models/endpoints.js, tests/integration/endpointRoutes.js
Url parameters are now supported and the logic that processes the retrieval of the url parameters (for use in external requests) expects the endpoint pattern to be valid, that is it should have parameter names. patterns like "/path/:/" and "/path/:" will result in the function that handles the request matching failing. The logic that is added in this commit ensures that the url patterns are valid
TRACE-178
=> add logic for validating endpoint patterns

src/middleware/externalRequests.js, src/middleware/initiate.js, src/middleware/parser.js, src/openhim.js
If the response from the upstream services is an OpenHIM response, we just need to take the entore body and send it to the OpenHIM for processing
TRACE-179
=> Allow OpenHIM responses to be passed to OpenHIM

src/middleware/externalRequests.js, src/middleware/mapper.js, src/middleware/validator.js, src/openhim.js, tests/integration/externalRequests.js, tests/integration/integration.js, tests/integration/mapper.js, tests/unit/mapper.js, tests/unit/openhim.js
This fixes a bug where orchestrations were being replaced instead of added to the existing array
Using "unshift" on an array is for adding individual items to the array (comma separated), but we need to append the entire array
"Concat" adds an existing array to antoher array without having to loop through each array item and then using "unshift"
https://www.w3schools.com/jsref/jsref_unshift.asp
https://www.w3schools.com/jsref/jsref_concat_array.asp
Edit
---------------------
Also updated the orchestration name to be a bit more descriptive.
Added in a orchestration for validation middleware
=> OHIE-431: orchestrations bug

src/middleware/externalRequests.js, tests/unit/externalRequests.js
The previous stringified JSON parsing logic did not cater for array
lookup requests. The nested data structures were ignored and therefore
the data was not accessible as it was still a string...
The logic now will go through each requests response in the array and
attempt to parse the response body if it is stringified JSON
DSC19-25
=> DSC19-25 Add logic to cater for array lookup requests to mediator

docs/docs/gettingStarted/endpoints.md
The forwardExistingRequestBody field must be set to true if you need to
access the incoming request payload (within items)
If the field is left out the request body will be set to `null`
DSC19-25
=> Update orchestration docs forEach info

README.md, docs/docs/gettingStarted/setup.md, mediatorConfig.json, package.json, src/middleware/externalRequests.js, tests/integration/externalRequests.js, tests/unit/externalRequests.js
Previously, if there were multiple response requests only the first
response would contain data - the others would be empty objects
This was due to a logic error associated with the array responses as in
that case the data did need to be cleared between requests
DSC19-96
=> DSC19-96 Ensure all response requests contain the mapped data

docs/docs/gettingStarted/endpoints.md, package.json, src/constants.js, src/db/models/endpoints.js, src/middleware/externalRequests.js, src/middleware/parser.js, src/util.js, tests/integration/endpointRoutes.js, tests/integration/externalRequests.js, tests/integration/integration.js, tests/integration/mapper.js, tests/integration/parser.js, tests/unit/cache.js, tests/unit/dbService.js, tests/unit/endpointRoutes.js, tests/unit/externalRequests.js, tests/unit/initiateMiddleware.js, tests/unit/mapper.js, tests/unit/openhim.js, tests/unit/orchestrations.js, tests/unit/parser.js, tests/unit/stateService.js, tests/unit/transformerMiddleware.js
Make the error returned more descriptive and add ability to return a fhir response error from a lookup or response request (done by specifying the property `fhirResponse`  to true in the endpoint schema
=> Tb 181 fix error handling
