endpoints/bahmni/input-mapping.json
This adds more mapping rules
OHM-871
=> add more fields to the mapping object

src/middleware/mapper.js, src/middleware/validator.js, src/routes.js
Each route created will have preset middleware attached.
Currently, the middleware has no real function.
It will be expanded on in future tasks
OHM-873
=> OHM-873 Add initial middleware structure

.travis.yml, package.json
Allow build health to be tracked
OHM-846
=> Add travis ci script

src/middleware/validator.js, src/routes.js
Shouldn't have been left there adter refactoring...
OH-871
=> Remove unused Variables

docs/Setup.md
=> documentation

package-lock.json, package.json
To ensure we stay up-to-date with the lastest versions and have no out-dated packages.
=> Updated the package dependency version to the latest versions

src/constants.js, src/middleware/mapper.js, src/middleware/parser.js, src/middleware/validator.js, src/routes.js
Just a few minor code cleanup additions and updates
=> Minor cleanup changes

src/middleware/mapper.js, src/middleware/parser.js, src/middleware/validator.js
Ensure that the payload returned to client when an exception is thrown, is the same content-type as the payload that was used to make the request.
=> Ohm 892 error response content type

docs/Setup.md
* To include updated Environment variables
* Add description for input-mapping definitions
* Minor text corrections
OHM-861
=> Updated documentation

README.md, src/logger.js
The LGTM service analyses the codebase for any code related issues
This is an automated integrated service when new PRs are submitted
https://lgtm.com/projects/g/jembi/openhim-mediator-mapping?mode=list
=> Added badges for LGTM integration

src/constants.js, src/db/models/states.js, src/db/services/states/index.js, src/middleware/initiate.js, tests/unit/initiateMiddleware.js, tests/unit/stateService.js, yarn.lock
So that we can be sure the correct data make it into the database
And any expected errors are thrown when data isnt valid
OHM-1011
=> OHM-1011: Add tests for testing the States DB services

tests/integration/endpointRoutes.js
These are the integration tests of the routes that are used for creating, reading, updating and deleting the mapping mediator ednpoints
OHM-1014
=> add integration tests for the endpoint routes

package.json
=> Updated package version to an official v1.0.0 release

package.json, yarn.lock
This isnt needed as we will be included the src directly into the build.
Babel doesnt need to do any kind of transpiling just yet
=> Removed the babel package and the build steps

README.md, docker-compose.deps.yml, docs/docs/endpoints.md, src/middleware/externalRequests.js, tests/integration/externalRequests.js, tests/integration/integration.js, tests/unit/externalRequests.js
**Note:** This is a major breaking change as the configuration for query parameters had to change to support this. This means a major version bump since we are at a stable major version.
=> OHIE-408 - URL params for external requests

src/middleware/externalRequests.js, tests/unit/externalRequests.js
We require access to all the data within allData to allow flexible
configuration
TRACE-156
=> Add transforms data to the extractable params

src/middleware/externalRequests.js, src/middleware/mapper.js, src/middleware/parser.js, src/orchestrations.js, tests/integration/externalRequests.js, tests/unit/orchestrations.js
This ensure that all parameters and data are resolved when creating orchestrations. This is the correct place to capture orchestration data as it represents the final state of the request.
=> OHIE-430 - Use axios config as source of orcehstration data

README.md, src/middleware/externalRequests.js, tests/integration/externalRequests.js, tests/unit/externalRequests.js, yarn.lock
This PR address a bug found where error responses are not returned correctly.
It returned all the chained response as part of the main response.
The response of the final downstream server should be returned in the response body
=> OHIE-431: response bug openhim

package.json
This is to include the missing feature that was mentioned in the previous release but not actually included.
This adds the support for Response requests to be sent out based on an Array of items
=> Updated package version with patch bump

mediatorConfig.json, package.json
To indiciate the additional feature that was added to the package
Feature added was to cater for HTTP status codes in the states collection, and the user configuration to determine the renage of status codes to do the lookup on for the last valid state record
=> Minor version increase

docs/package.json, docs/yarn.lock
=> Update node dependencies to latest

.github/workflows/docker-image-scan.yml, .github/workflows/docker-publish.yml
=> Add github actions for pushing and scanning docker images
